sudo: required
services:
  - docker
language: go
go:
  - "1.12.x"
env:
  - GO111MODULE=on make build

install:
  - go mod download

script:
  - make check

before_deploy:
  - make agent-docker

deploy:
  - provider: script
    script: bash ./scripts/docker_push.sh
    on:
      branch: aarch64
arch:
  - arm64
os: linux 