sudo: required
services:
  - docker
language: go
go:
  - "1.15.x"
env:
  - make build

install:
  - go mod download

script:
  - make check

before_deploy:
  - make agent-docker

deploy:
  - provider: script
    script: bash ./scripts/my_docker_push.sh
    on:
      branch: x86_64
arch:
  - amd64
os: linux 
